Lesson 3
js-tasks-ru/jsbasic-20210621_natalie-iv pull request #4
Opened 2021-07-06 22:04 UTC by Orangesad

Task 1, 2, 3, 4, 5

2021-07-06 22:05 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-07 16:49 UTC, SinimaWath requested changes
Подмержи себе upstream плиз: `git pull upstream master`

2021-07-07 16:49 UTC, SinimaWath commented on 3-module/2-task/index.js
> +//todo: Сократить до (a <= item <= b) не выходит, почему-то тест на диапазон не проходит :(
Такой конструкции нет в JavaScript,  так что, да, не работает

2021-07-07 16:49 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return str.replace(/-/g, "-:")
Давай попробуем написать без -:  . Это немного лишнее.

Понять, что не нужно делать upperCase можно через index === 0 ;)

2021-07-07 16:49 UTC, SinimaWath commented on 3-module/4-task/index.js
> +              .map(user => {return `${user.name}, ${user.balance}`;})
тут return лишний, давай в краткой форме напишем:
`user => ....`

2021-07-07 16:49 UTC, SinimaWath commented on 3-module/5-task/index.js
> +    max: Math.max.apply(null, numbers),
тут более красиво будет spread оператор, давай используем его, а не apply.

2021-07-07 19:17 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-07 22:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-08 11:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-10 15:30 UTC, SinimaWath approved these changes
с 4 модулем все круто, молодец

2021-07-10 15:31 UTC, merged