Module 6, Tasks 1, 2, 3
js-tasks-ru/jsbasic-20210621_natalie-iv pull request #6
Opened 2021-07-25 20:55 UTC by Orangesad

Прошу обратить внимание, что у меня в 3 задании стоит "просмотрено решение преподавателя", я вам уже писала об этом в слаке. 
У меня было свое решение на 3 задании, чтобы прошли тесты я подправила свое решение с примесью "решения преподавателя" (добавила апдейт).

2021-07-25 21:07 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-25 21:49 UTC, SinimaWath requested changes

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/2-task/index.js
> +  get elem() {
В твоей реализации, обращение к elem - создает новые DOM-елемент каждый раз. К сожалению, в описании задачи, не написанно, что так нельзя ( Я это добавлю.

Но твой компонент, могут использовать несколько раз:
```
const productCard = new ProductCard(...);

productCard.elem; //  получили dom-елемент
productCard.elem; // хотим получить тот же, но он уже другой. И тут баг (

```

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/2-task/index.js
> +      document.body.dispatchEvent(event);
dispatchEvent лучше делать на this.card.

Это будет работать, если поправить комментарий, который я выше описал.

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/3-task/my.js
> +      let button = this.elem.getElementsByClassName('carousel__button')[i];
нет необходимости искать кнопку от `this.elem`. Можешь ее найти из card.  В таком случае, не нужен будет костыль с поиском елемента по индексу и код будет проще

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/3-task/my.js
> +  addCard(id) {
метод называется addCard - но по факту он не добавляет карточку (

Это проблема для других разработчиков, которые будут твой код читать.

в твоем случае, метод должен, к примеру, называться: `dispatchProductAddEvent`

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/3-task/my.js
> +    document.body.dispatchEvent(event);
лучше диспатчить событие не на body, а на контейнер елемент (это будет работать, так как событие  bubbles: true)

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/3-task/my.js
> +    console.log(offset);
Лучше в продакшн коде убирать консоль логи

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/1-task/index.js
> +  deleteTableRow () {
метод называется deleteTableRow - но ничего не удаляет (

Это проблема для других разработчиков, которые будут твой код читать, название метода должно описывать зачем он.

в твоем случае, метод должен, к примеру, называться: `addTableDeleteRowListener`

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/1-task/index.js
> +    this.elem.dataset.component = 'usersTable';
Хорошая идея! 

Только по коду почему-то не используешь (

2021-07-25 21:49 UTC, SinimaWath commented on 6-module/1-task/index.js
> +      let button = target.closest("button");
Метод closest ищет елемент по селектору. В этом случае - это оверхед, тебе достаточно проверить, что target - это button: `target.tagName === 'BUTTON'` или через dataset атрибут

2021-07-27 14:42 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-27 15:36 UTC, SinimaWath approved these changes

2021-07-27 15:36 UTC, merged